name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Lint
      run: npx ts-standard src
    - run: npm run build
    - run: mv build ~/build-${{ github.sha }}

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ github.sha }}
        path: ~/build-${{ github.sha }}
        if-no-files-found: error

  production-deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build-${{ github.sha }}
        path: ~/build-${{ github.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: S3 copy
      run: aws s3 cp ~/build-${{ github.sha }} s3://spotifydigger.app/ --recursive
